Dev/front modify
swsnu/swpp2019-team2 pull request #72
Opened 2019-11-12 17:52 UTC by xixili3

FE Lip action modified

frontend/src/store/actions/cosmos.js - 'getLips' action modified
frontend/src/Containers/Search.js - 'result' string parameter modified
규칙: 예) Lip -> Category: stick & tint -> Color: red 이면 /api/lip/category=stick&category=tint&color=red& URL로 GET.

2019-11-12 18:02 UTC, xixili3 commented
소나클라우드는 테스트 코드 커버리지 문제인데 아침 일찍일어나서 마무리 짓겠습니다.

2019-11-13 05:28 UTC, xixili3 commented
테스팅 마무리 지었습니다

2019-11-13 08:31 UTC, aeri206 requested changes
Request URL 규칙에 대해서 이슈에 남겨주세요

2019-11-13 08:31 UTC, aeri206 commented on frontend/src/Containers/Search.js
> +  handleClickRed() { // tone1 태그 선택
주석 // Tone1 -> // red

2019-11-13 08:31 UTC, aeri206 commented on frontend/src/Containers/Search.js
> +            lipResult = this.props.storedLips.map((cosmos) => (
BE 결과값 받아오면서 바꿔야 할 것 같긴한데, Lip model 안에 있는  field만 반영해서 JS 코드 짜는게 좋을거 같습니다
현재 Django Lip model에는 color property가 없습니다

2019-11-13 08:31 UTC, aeri206 commented on frontend/src/Containers/Search.js
> +              <button type="button" className={this.state.button_red ? 'buttonTrue' : 'buttonFalse'} id="SkinTone-1" onClick={() => this.handleClickRed()}>Red</button>
button ID도 같이 변경해주세요

2019-11-13 16:52 UTC, xixili3 commented on frontend/src/Containers/Search.js
> +  handleClickRed() { // tone1 태그 선택
주석 변경 완료 했습니다~

2019-11-13 16:53 UTC, xixili3 commented on frontend/src/Containers/Search.js
> +            lipResult = this.props.storedLips.map((cosmos) => (
네. 현재 Lip 모델에 따라서 color 필드를 삭제하고 form 필드를 넣어줬습니당

2019-11-13 16:53 UTC, xixili3 commented on frontend/src/Containers/Search.js
> +              <button type="button" className={this.state.button_red ? 'buttonTrue' : 'buttonFalse'} id="SkinTone-1" onClick={() => this.handleClickRed()}>Red</button>
변경해줬습니다.

2019-11-13 18:51 UTC, aeri206 approved these changes

2019-11-13 18:59 UTC, das425 approved these changes
고생하셨습니다 :)

2019-11-14 08:34 UTC, merged